deployment:
  version: IMAGE_VERSION
  imageURL: 435238037339.dkr.ecr.us-east-1.amazonaws.com/expense/frontend
  replicas: 2
hpa:
  minreplicas: 1
  maxreplicas: 10
  cpuutilisation: 5
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:435238037339:targetgroup/nginx/405f50512d6b622f